# Generated by Django 3.1 on 2022-01-03 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название рига')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание рига')),
                ('color', models.CharField(blank=True, max_length=6, verbose_name='Цвет')),
                ('server', models.CharField(blank=True, max_length=255, verbose_name='Сервер Пула')),
                ('miner_worker', models.CharField(blank=True, max_length=255, verbose_name='Воркер')),
                ('bat', models.TextField(blank=True, max_length=1000, verbose_name='Батник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец рига')),
            ],
            options={
                'verbose_name': 'Риг',
                'verbose_name_plural': 'Риги',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата создания')),
                ('electricity', models.FloatField(blank=True, verbose_name='Энергии сожрал')),
                ('speed', models.FloatField(blank=True, verbose_name='Скорость в майнере')),
                ('power', models.IntegerField(blank=True, verbose_name='Потребление ватт/час')),
                ('temperature', models.IntegerField(blank=True, verbose_name='Температура')),
                ('memory_clock', models.IntegerField(blank=True, verbose_name='Частота памяти')),
                ('core_clock', models.IntegerField(blank=True, verbose_name='Частота ядра')),
                ('pool_speed', models.FloatField(blank=True, verbose_name='Скорость на пуле')),
                ('server', models.CharField(blank=True, max_length=255, verbose_name='Сервер пула')),
                ('shares_per_minute', models.FloatField(blank=True, verbose_name='Решений в минуту')),
                ('accepted_shares', models.IntegerField(blank=True, verbose_name='Принятые решения')),
                ('invalid_shares', models.IntegerField(blank=True, verbose_name='Неправильные решения')),
                ('rejected_shares', models.IntegerField(blank=True, verbose_name='Отклоненные решения')),
                ('stale_shares', models.IntegerField(blank=True, verbose_name='Опаздавшие решения')),
                ('uptime', models.IntegerField(blank=True, verbose_name='Аптайм')),
                ('miner_worker', models.CharField(blank=True, max_length=255, verbose_name='Воркер')),
                ('miner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miner.miner', verbose_name='Риг')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ('-id',),
            },
        ),
    ]
